name: Deploy bicep

on:
  workflow_call:     
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:        
        required: true
      RESOURCE_GROUP_NAME:        
        required: true

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3

    - name: 'az login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
    - name: Bicep What-If
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment group what-if --mode incremental --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --template-file foo.bicep

    # some additional checks? meeeeh.. maybe
    - name: Bicep Deploy
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment group create --mode incremental --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --template-file foo.bicep